### ISSUE TITLE
subclasses for electrochemical cell

### ISSUE THREAD

**Issue by schaferw** [rsc-ontologies/rsc-cmo#18]
PROCO has the need for the following terms which would appear to be better placed in CHMO.

divided electrochemical cell - electrochemical cell where the anode and cathode are placed in different vessels requiring the use of a salt bridge, frit or membrane to complete the circuit.
undivided electrochemical cell - electrochemical cell where the anode and cathode are placed in the same vessel.

**Comment by batchelorc** [comment]
This works. They will be children of "electrochemical cell" CHMO_0002351.

Do you have an ORCiD we can use as a source? Or is there a specific reference you'd like?

All the best,
Colin.

**Comment by schaferw** [comment]
Thanks for the very prompt response.

My ORCiD is https://orcid.org/0000-0002-8786-1756 (Schafer, Wes)

Could you tell us about how long it takes for the IRI to be minted or how long before the new terms are released?

Best regards,
Wes

**Comment by batchelorc** [comment]
Should be able to do it today.

**Comment by batchelorc** [comment]
*ahem* Friday, sorry.

**Comment by batchelorc** [comment]
CHMO_0002929 is the divided one, CHMO_0002930 undivided. Many thanks!

**Comment by schaferw** [comment]
No issues.  That’s still a very rapid response.
