### ISSUE TITLE
Sync chmo.owl with chmo.obo in a new release

### ISSUE THREAD

**Issue by StroemPhi** [rsc-ontologies/rsc-cmo#27]
The PR (#25) fixed an error in the chmo.obo file which was introduced in https://github.com/rsc-ontologies/rsc-cmo/commit/6e2fa549e91c8418be9a7566dcb4640ba26901cd#diff-4155d58012896cfdbed35c6880987191d8f3a103e9a2631ba643fa911b8e3470R29976-R29982.
Unfortunately, the corrected OBO was not converted to OWL in this PR to also fix the wrong parent that was a result of the error in this commit.
So a new release should be made that syncs the outdated OWL with the current OBO, by recreating it from the OBO as described in the README.

**Comment by hujo91** [comment]
Hi,

@batchelorc could you please take care of this.

Many thanks!!!

**Comment by batchelorc** [comment]
Should be done now. Apologies for wrong issue number in the commit notice
