### ISSUE TITLE
chmo IRI is invalid

### ISSUE THREAD

**Issue by JKChang2015** [rsc-ontologies/rsc-cmo#4]
Hi,
The IRI/URL of Chemical Methods Ontology is no longer available (http://purl.obolibrary.org/obo/chmo). Could you please help to fix it? 
Thank you.

**Comment by rsc-ontologies** [comment]
Yes of course.

**Comment by cmungall** [comment]
The correct PURL for the ontology is http://purl.obolibrary.org/obo/chmo.owl

Class PURLs are of the form http://purl.obolibrary.org/obo/CHMO_0000161

I think this issue can be closed?
