### ISSUE TITLE
CHMO:000283 - Request revision of text definition

### ISSUE THREAD

**Issue by lizumberfield** [rsc-ontologies/rsc-cmo#6]
CHMO:0002832 'Material Disposal' was recently imported into the Informed Consent Ontology following an evaluation of clinical consent forms and permissions to store/use leftover biospecimens collected during clinical care. 

The text definition almost meets our need, but is slightly too specific. Would you consider revising this definition to read as:
"_A planned process in which materials are removed permanently from a laboratory or repository_"
This would involve deleting 'for an experiment' (clinical biospecimens can be stored for a range of uses, often unknown at the time of collection but may include research) and adding 'or repository' (consent forms often contain conditions for disposal of biospecimens, but they may be in storage rather than a lab).

Thanks for considering.
[Elizabeth Umberfield](https://orcid.org/0000-0001-5029-1158)

**Comment by batchelorc** [comment]
This I have done. Thank you for your interest in CHMO!

**Comment by lizumberfield** [comment]
Thanks!
