### ISSUE TITLE
Replacing caused by (CHMO:0010021) with a RO relation?

### ISSUE THREAD

**Issue by StroemPhi** [rsc-ontologies/rsc-cmo#9]
The 'caused by' ([CHMO:0010021](http://purl.obolibrary.org/obo/CHMO_0010021)) relation contains the comment:

> this is a placeholder. Not sure why this isn't covered by BFO or RO tbh.

In RO there are quite a few relations under 'causal relation between processes' ([RO:0002501](http://purl.obolibrary.org/obo/RO_0002501)). Is there a reason the CHMO placeholder term is not replaced with one of these?

**Comment by rsc-ontologies** [comment]
You're right - it's best to replace this placeholder with one of the RO relations, even if they too are placeholders. Many thanks!

**Comment by StroemPhi** [comment]
From the curator note on RO:0002501, I think only this is a placeholder/grouping relation not its children. 
So far the CHMO 'caused by' is only used for the subclassing of 'injury by flying debris' (CHMO:0010022) with the axiom:
`'caused by' some 'laboratory uncontrolled explosion'`
In this case, I think the definition of 'causally upstream of' [RO:0002411](http://purl.obolibrary.org/obo/RO_0002411) fits best.
